### ISSUE TITLE
Please add Window Shade capability to the Dimmer driver version

### ISSUE THREAD

**Issue by amithalp** [jvmahon/HubitatCustom#11]
When using the current driver version with a Fibaro FGR-223 Roller Shutter device and setting the level to be zero (fully closed), the shade will fully close but level value will not be changed to zero but rather remain as it was before apllying the close command.
In reply to my question you stated that this could be resolved by adding a Window Shade capability and then you could install the driver and un-comment or comment that to determine if it should work in "Shade" mode or "Dimmer" mode.

**Comment by jvmahon** [comment]
Added in 0.1.1 of the dimmer driver.
Just un-comment the "WindowShade" capability, and comment out "Switch" and "SwitchLevel"
Re-open if there are problems.
