### ISSUE TITLE
Minoston MS11Z - Dimmer Switch - MissingMethodException

### ISSUE THREAD

**Issue by andrepintorj** [jvmahon/HubitatCustom#15]
Hi, first of all, thanks for your hardwork on this device driver! It seems pretty amazing. Today I saw this debug message being thrown. Not sure exactly what is this error... If it is relevant or not:

Error in parse() attempting to parse input: zw device: 19, command: 6C01, payload: 09 03 20 03 00 , isMulticast: false. 
Error: groovy.lang.MissingMethodException: No signature of method: hubitat.zwave.commands.supervisionv1.SupervisionGet.encapsulatedCommand() is applicable for argument types: (null, java.util.LinkedHashMap) values: [null, [32:2, 37:2, 38:4, 49:11, 50:5, 91:3, 96:4, 98:1, 99:1, ...]]
Possible solutions: encapsulatedCommand(java.util.Map). 
Stack trace is: groovy.lang.MissingMethodException: No signature of method: hubitat.zwave.commands.supervisionv1.SupervisionGet.encapsulatedCommand() is applicable for argument types: (null, java.util.LinkedHashMap) values: [null, [32:2, 37:2, 38:4, 49:11, 50:5, 91:3, 96:4, 98:1, 99:1, ...]]
Possible solutions: encapsulatedCommand(java.util.Map)
  at user_driver_jvm__Beta_0_1_3__Almost_Any_Dimmer_Z_wave_Plus_Dimmer_Driver_560.zwaveEvent(user_driver_jvm__Beta_0_1_3__Almost_Any_Dimmer_Z_wave_Plus_Dimmer_Driver_560.groovy:1904)
  at user_driver_jvm__Beta_0_1_3__Almost_Any_Dimmer_Z_wave_Plus_Dimmer_Driver_560.zwaveEvent(user_driver_jvm__Beta_0_1_3__Almost_Any_Dimmer_Z_wave_Plus_Dimmer_Driver_560.groovy)
  at user_driver_jvm__Beta_0_1_3__Almost_Any_Dimmer_Z_wave_Plus_Dimmer_Driver_560.parse(user_driver_jvm__Beta_0_1_3__Almost_Any_Dimmer_Z_wave_Plus_Dimmer_Driver_560.groovy:2011).
Exception message is groovy.lang.MissingMethodException: No signature of method: hubitat.zwave.commands.supervisionv1.SupervisionGet.encapsulatedCommand() is applicable for argument types: (null, java.util.LinkedHashMap) values: [null, [32:2, 37:2, 38:4, 49:11, 50:5, 91:3, 96:4, 98:1, 99:1, ...]]
Possible solutions: encapsulatedCommand(java.util.Map) on line 1904. 
Parse map is: [32:2, 37:2, 38:4, 49:11, 50:5, 91:3, 96:4, 98:1, 99:1, 108:1, 113:8, 114:1, 128:1, 134:3, 152:1, 155:2, 135:3].

**Comment by jvmahon** [comment]
That looks like a bug in the driver.
I just posted an updated version (0.1.4) - see if that fixes it.

Also, what type of device was it, and was it included using S2 encryption?

PS - thanks for including all of the details, it made it easy to find the problem.

**Comment by andrepintorj** [comment]
Great! I'll test the new version, thank you!
The device is a "[Minoston In-Wall Smart Dimmer Switch (MS11Z)](https://minoston.com/wp-content/uploads/2020/08/MS11Z-Manual.pdf)".
And yes, it was added to the controller using S2.

**Comment by jvmahon** [comment]
None of my devices are paired using S2, so I didn't test that fully. If the update doesn't work, I'll repair some of my devices with S2 so I can fix this. It shouldn't be a big deal to do that if needed.

**Comment by jvmahon** [comment]
Fixed another bug. Try 0.1.5

**Comment by andrepintorj** [comment]
At least, with 0.1.4 the error I reported didn't show up again. Now testing 0.1.5. TY!

**Comment by jvmahon** [comment]
In 0.1.4, there was an error when using Central Scene devices that were included using S2. That was fixed in 0.1.5.

**Comment by jvmahon** [comment]
Ugh. I'm finding there are multiple problems using S2 security.
I hope to get them fixed quickly, but its a bit tricky.

**Comment by jvmahon** [comment]
This should be fixed now, and I've moved the driver release to 1.0.0 (non-beta). Re-open the comment if you continue to have issues.
