### ISSUE TITLE
Error on setParameter command to HomeSeer WD200+

### ISSUE THREAD

**Issue by gwalker88** [jvmahon/HubitatCustom#20]
I am getting errors when sending certain LED parameters via Z-Wave to HS-WD200+ switches:

> dev:12812021-06-23 02:49:58.510 pm infoDevice Kitchen Pendants: Device successfully processed supervised command 9F03016C01A70570041B0101.
> dev:12812021-06-23 02:49:57.298 pm errororg.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object 'true' with class 'java.lang.Boolean' to class 'hubitat.zwave.Command' on line 722 (setParameter)
> dev:12812021-06-23 02:49:57.272 pm infoDevice Kitchen Pendants: updating parameter: 26 to 0.
> dev:12812021-06-23 02:49:37.639 pm infoDevice Kitchen Pendants: Device successfully processed supervised command 9F03016C01A6057004190102.
> dev:12812021-06-23 02:49:36.462 pm errororg.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object 'true' with class 'java.lang.Boolean' to class 'hubitat.zwave.Command' on line 722 (setParameter)
> dev:12812021-06-23 02:49:36.408 pm infoDevice Kitchen Pendants: updating parameter: 24 to 6.
> dev:12812021-06-23 02:49:16.724 pm infoDevice Kitchen Pendants: Device successfully processed supervised command 9F03016C01A5057004170101.
> dev:12812021-06-23 02:48:56.495 pm infoDevice Kitchen Pendants: Device successfully processed supervised command 9F03016C01A4057004160102.

I have identical actions for each of the 7 LEDs, which merely update the colour based upon the value of a number variable (LED1status, LED2status, etc.). All are defined in RM as "number" not decimal, so I can't fathom where the "cast" error for setParameter is going wrong on some of my LEDs and not others. But the end result is that some of my LEDs change colour reliably, and others don't.

Anyway, I've attached the above log as a starting point--please let me know if you would like additional logs or info, or whether you think this is a case for Hubitat support.

**Comment by jvmahon** [comment]
Try the latest update - v1.1.8 and let me know if that works for you.

**Comment by gwalker88** [comment]
That seems to have worked a treat. I’ll keep an eye on it for the next couple of days, but go ahead and close this issue, and I’ll open a new one with debug logs if it recurs.
